#!/bin/bash

script/branding

: ${LIBSASS_SPEC_PATH:="libsass-spec"}
: ${SASS_SPEC_PATH:="sass-spec"}
: ${SASS_SASSC_PATH:="sassc" }

if [ ! -d $SASS_SPEC_PATH ]; then
  git clone https://github.com/mgreter/sass-spec-ng.git --branch libsass-ng $SASS_SPEC_PATH
fi
if [ ! -d $SASS_SASSC_PATH ]; then
  git clone https://github.com/mgreter/sassc-ng.git --branch libsass-ng $SASS_SASSC_PATH
fi
