name: GitHub CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:

  linux-and-mac:
    name: GNU
    # if: ${{ false }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # NO-CI - {os: ubuntu-20.04, build: 'static', cc: 'gcc-4.4', cxx: 'g++-4.4', autotools: 'no', cppstd: 'gnu++0x'}
          # NO-CI - {os: ubuntu-20.04, build: 'static', cc: 'gcc-4.5', cxx: 'g++-4.5', autotools: 'no', cppstd: 'gnu++0x'}
          # NO-CI - {os: ubuntu-20.04, build: 'static', cc: 'gcc-4.6', cxx: 'g++-4.6', autotools: 'no', cppstd: 'gnu++0x'}
          - {os: ubuntu-20.04, build: 'static', cc: 'gcc-4.7', cxx: 'g++-4.7', autotools: 'no', cppstd: 'gnu++11'}
          - {os: ubuntu-20.04, build: 'static', cc: 'gcc-4.8', cxx: 'g++-4.8', autotools: 'no', cppstd: 'c++11'}
          - {os: ubuntu-20.04, build: 'static', cc: 'gcc-5', cxx: 'g++-5', autotools: 'no', cppstd: 'c++11'}
          # NO-CI - {os: ubuntu-20.04, build: 'static', cc: 'gcc-6', cxx: 'g++-6', autotools: 'no', cppstd: 'c++11'}
          - {os: ubuntu-20.04, build: 'static', cc: 'gcc-7', cxx: 'g++-7', autotools: 'no', cppstd: 'c++11'}
          - {os: ubuntu-latest, build: 'shared', cc: 'gcc', cxx: 'g++', autotools: 'yes', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: ubuntu-latest, build: 'static', cc: 'gcc', cxx: 'g++', autotools: 'yes', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: ubuntu-latest, build: 'shared', cc: 'gcc', cxx: 'g++', autotools: 'no', cppstd: 'c++11'}
          - {os: ubuntu-latest, build: 'static', cc: 'gcc', cxx: 'g++', autotools: 'no', cppstd: 'c++11'}
          - {os: ubuntu-latest, build: 'shared', cc: 'clang', cxx: 'clang++', autotools: 'yes', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: ubuntu-latest, build: 'static', cc: 'clang', cxx: 'clang++', autotools: 'yes', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: ubuntu-latest, build: 'shared', cc: 'clang', cxx: 'clang++', autotools: 'no', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: ubuntu-latest, build: 'static', cc: 'clang', cxx: 'clang++', autotools: 'no', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: macOS-latest, build: 'shared', cc: 'clang', cxx: 'clang++', autotools: 'yes', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: macOS-latest, build: 'static', cc: 'clang', cxx: 'clang++', autotools: 'yes', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: macOS-latest, build: 'shared', cc: 'clang', cxx: 'clang++', autotools: 'no', cppstd: 'c++11', cflags: '-g -fsanitize=address'}
          - {os: macOS-latest, build: 'static', cc: 'clang', cxx: 'clang++', autotools: 'no', cppstd: 'c++11', cflags: '-g -fsanitize=address'}

    env:
      ASAN_OPTIONS: ${{ matrix.config.asan }}
      AUTOTOOLS: ${{ matrix.config.autotools }}
      EXTRA_CFLAGS: ${{ matrix.config.cflags }}
      EXTRA_CXXFLAGS: ${{ matrix.config.cflags }}
      EXTRA_LDFLAGS: ${{ matrix.config.cflags }}
      SASS_LIBSASS_PATH: libsass
      COVERAGE: no
      BUILD: ${{ matrix.config.build }}
      CXX: ${{ matrix.config.cxx }}
      CC: ${{ matrix.config.cc }}

    steps:
    - uses: actions/checkout@v4
    - name: Install gcc 7 if needed
      if: matrix.config.cc == 'gcc-7'
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu focal main universe"
        sudo apt update
        sudo apt install g++-7 gcc-7 -y
    - name: Install gcc 6 if needed
      if: matrix.config.cc == 'gcc-6'
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main"
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial universe"
        sudo apt update
        sudo apt install g++-6 gcc-6 -y
    - name: Install gcc 5 if needed
      if: matrix.config.cc == 'gcc-5'
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main"
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial universe"
        sudo apt update
        sudo apt install g++-5 -y
    - name: Install gcc 4.8 if needed
      if: matrix.config.cc == 'gcc-4.8'
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main"
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial universe"
        sudo apt update
        sudo apt install g++-4.8 -y
    - name: Install gcc 4.7 if needed
      if: matrix.config.cc == 'gcc-4.7'
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main"
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial universe"
        sudo apt update
        sudo apt install g++-4.7 -y
    - name: Install gcc 4.6 if needed
      if: matrix.config.cc == 'gcc-4.6'
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main"
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial universe"
        sudo apt update
        sudo apt install g++-4.6 -y
    - name: Install gcc 4.5 if needed
      if: matrix.config.cc == 'gcc-4.5'
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main"
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial universe"
        sudo apt update
        sudo apt install g++-4.5 -y
    - name: Install gcc 4.4 if needed
      if: matrix.config.cc == 'gcc-4.4'
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main"
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial universe"
        sudo apt update
        sudo apt install g++-4.4 -y
    - name: Install autotools on MacOS
      if: matrix.config.os == 'macOS-latest'
      run: brew install autoconf automake libtool
    - name: ./script/ci-install-deps
      env:
        MAKE_OPTS: LIBSASS_CPPSTD=${{ matrix.config.cppstd }}
      run: ./script/ci-install-deps
    - name: ./script/ci-install-compiler
      env:
        MAKE_OPTS: LIBSASS_CPPSTD=${{ matrix.config.cppstd }}
      run: ./script/ci-install-compiler
    - name: ./script/ci-build-libsass
      env:
        MAKE_OPTS: LIBSASS_CPPSTD=${{ matrix.config.cppstd }}
      run: ./script/ci-build-libsass
    - name: Call LibSass make install
      run: sudo EXTRA_CFLAGS="$EXTRA_CFLAGS" EXTRA_CXXFLAGS="$EXTRA_CXXFLAGS" EXTRA_LDFLAGS="$EXTRA_LDFLAGS" make install
    - name: Call SassC make install
      run: sudo EXTRA_CFLAGS="$EXTRA_CFLAGS" EXTRA_CXXFLAGS="$EXTRA_CXXFLAGS" EXTRA_LDFLAGS="$EXTRA_LDFLAGS" make -C sassc install
    - name: Check sassc help call
      run: sassc --term-colors --help


  windows-msvc:
    runs-on: ${{ matrix.config.os }}
    name: MSVC
    if: ${{ false }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: 'windows-latest', build: Release, platform: x64, version: 'latest'}
          - {os: 'windows-latest', build: Release, platform: x86, version: 'latest'}
          #- {os: 'windows-latest', build: Release, platform: arm64, version: 'latest'}
          - {os: 'windows-latest', build: Release, platform: arm, version: 'latest'}
          - {os: 'windows-latest', build: Debug, platform: x64, version: 'latest'}
          - {os: 'windows-latest', build: Debug, platform: x86, version: 'latest'}
          #- {os: 'windows-latest', build: Debug, platform: arm64, version: 'latest'}
          - {os: 'windows-latest', build: Debug, platform: arm, version: 'latest'}
          - {os: 'windows-2019', build: Release, platform: x64, version: '[16.0,16.99]'}
          - {os: 'windows-2019', build: Release, platform: x86, version: '[16.0,16.99]'}
          #- {os: 'windows-2019', build: Release, platform: arm64, version: '[16.0,16.99]'}
          - {os: 'windows-2019', build: Release, platform: arm, version: '[16.0,16.99]'}
          - {os: 'windows-2019', build: Debug, platform: x64, version: '[16.0,16.99]'}
          - {os: 'windows-2019', build: Debug, platform: x86, version: '[16.0,16.99]'}
          #- {os: 'windows-2019', build: Debug, platform: arm64, version: '[16.0,16.99]'}
          - {os: 'windows-2019', build: Debug, platform: arm, version: '[16.0,16.99]'}

    steps:
    - name: Change git config to preserve line-endings
      run: |
        git config --system core.autocrlf false
        git config --system core.eol lf
    - uses: actions/checkout@v4
    - name: Add ASAN DLL directory to PATH
      if: ${{ matrix.config.build == 'Debug' }}
      shell: pwsh
      run: |
        $installDir=(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath)
        echo "Detected MSVC install dir: \"${installDir}\""
        if ("${{ 'msvc' }}" -eq "msvc") {
          if (Test-Path -Path "${installDir}\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt") {
            $vctoolsVersion=(Get-Content -Path "${installDir}\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt")
            echo "Detected VCTools version: ${vctoolsVersion}"
          } else {
            echo "Failed to detect MSVC version"
            exit 1
          }
          dir "${installDir}\VC\Tools\MSVC\${vctoolsVersion}\bin"
          dir "${installDir}\VC\Tools\MSVC\${vctoolsVersion}\bin\arm64"
          "${installDir}\VC\Tools\MSVC\${vctoolsVersion}\bin\HostX64\${{ matrix.config.platform }}" >> $env:GITHUB_PATH
        } else {
          $clangVersion=((& "${installDir}\VC\Tools\Llvm\x64\bin\clang.exe" --version) | Select-String -Pattern "\d+.\d+.\d+" | % { $_.Matches } | % { $_.Value })
          echo "Detected clang version: ${clangVersion}"
          "${installDir}\VC\Tools\Llvm\x64\lib\clang\${clangVersion}\lib\windows" >> $env:GITHUB_PATH
        }
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: ${{ matrix.config.version }}
        msbuild-architecture: ${{ matrix.config.platform }}
    - name: Clone and checkout sassc repository
      run: git clone https://github.com/mgreter/sassc-ng.git --branch libsass-ng sassc
    - name: Clone and checkout sass-spec repository
      run: git clone https://github.com/mgreter/sass-spec-ng.git --branch libsass-ng sass-spec
    - name: Compile libsass ${{ matrix.config.build }} build for ${{ matrix.config.platform }}
      run: msbuild /m:4 /p:Configuration=${{ matrix.config.build }} /p:Platform=${{ matrix.config.platform }} sassc\win\sassc.sln
    - name: Listening results
      run: dir sassc\bin
    - name: Check sassc help call
      if: matrix.config.platform != 'arm' && matrix.config.platform != 'arm64'
      run: sassc\bin\sassc.exe --term-colors --help
    - name: Bootstrap spec test runner
      if: matrix.config.platform != 'arm' && matrix.config.platform != 'arm64'
      run: npm --prefix sass-spec ci
    - name: Execute spec test runner
      if: matrix.config.platform != 'arm' && matrix.config.platform != 'arm64'
      run: npm --prefix sass-spec run sass-spec -- -c "../sassc/bin/sassc.exe" --impl "libsass"

  windows-mingw:
    runs-on: windows-latest
    name: MinGW
    if: ${{ false }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {build: static, platform: x64, version: 13.2.0}
          - {build: static, platform: x64, version: 12.2.0}
          - {build: static, platform: x64, version: 11.2.0}
          - {build: static, platform: x64, version: 10.3.0}
          - {build: shared, platform: x64, version: 13.2.0}
          - {build: shared, platform: x64, version: 12.2.0}
          - {build: shared, platform: x64, version: 11.2.0}
          - {build: shared, platform: x64, version: 10.3.0}
          - {build: static, platform: x86, version: 13.2.0}
          - {build: static, platform: x86, version: 12.2.0}
          - {build: static, platform: x86, version: 11.2.0}
          - {build: static, platform: x86, version: 10.3.0}
          - {build: shared, platform: x86, version: 13.2.0}
          - {build: shared, platform: x86, version: 12.2.0}
          - {build: shared, platform: x86, version: 11.2.0}
          - {build: shared, platform: x86, version: 10.3.0}

    env:
      ASAN_OPTIONS: ${{ matrix.config.asan }}
      EXTRA_CFLAGS: ${{ matrix.config.cflags }}
      EXTRA_CXXFLAGS: ${{ matrix.config.cflags }}
      #SASS_LIBSASS_PATH: libsass
      #COVERAGE: no

    steps:
    - name: Change git config to preserve line-endings
      run: |
        git config --system core.autocrlf false
        git config --system core.eol lf
    - uses: actions/checkout@v4
    - name: Set up MinGW
      # uses: egor-tensin/setup-mingw@v2.2.0
      uses: ocbnet/setup-mingw@master
      with:
        version: ${{ matrix.config.version }}
        platform: ${{ matrix.config.platform }}
    - name: Clone and checkout sassc repository
      run: git clone https://github.com/mgreter/sassc-ng.git --branch libsass-ng sassc
    - name: Clone and checkout sass-spec repository
      run: git clone https://github.com/mgreter/sass-spec-ng.git --branch libsass-ng sass-spec
    - name: Compile libsass ${{ matrix.config.build }} build for ${{ matrix.config.platform }}
      run: make -j5 ${{ matrix.config.build }} BUILD=${{ matrix.config.build }} CC=gcc
    - name: Listening results
      run: dir lib
    - name: Copy library over to pass call test
      if: matrix.config.build == 'shared'
      run: copy lib\libsass.dll sassc\bin
    - name: Compile sassc ${{ matrix.config.build }} build for ${{ matrix.config.platform }}
      run: make -j5 sassc BUILD=${{ matrix.config.build }} CC=gcc
    - name: Check sassc help call
      run: sassc\bin\sassc.exe --term-colors --help
    - name: Bootstrap spec test runner
      if: matrix.config.build != 'Debug'
      run: npm --prefix sass-spec ci
    - name: Execute spec test runner
      if: matrix.config.build != 'Debug'
      run: npm --prefix sass-spec run sass-spec -- -c "../sassc/bin/sassc.exe" --impl "libsass"

#- name: Install LLVM and Clang
#  uses: KyleMayes/install-llvm-action@v1.2.2
